### ISSUE TITLE
selftemplating doesn't work if string contains single quote

### ISSUE THREAD

**Issue by wozniakjan** [cisco-sso/mh#26]
Mocked example, similar to one of our auth files where value contains `'`

`cat ./file.yaml`
```yaml
file:
  foo:
    bar:
      value: "abc'def"
```
```yaml
gomplate:
  datasources:
  - "file=./file.yaml"
  datasourceheaders: []:
test_val: "[[ (index (ds 'file').foo 'bar').value ]]"
```

fails with random `error converting YAML to JSON: yaml: line 5: did not find expected key"` on second iteration of selftemplating, but is broken in first iteration as well because it passes forward
```yaml
gomplate:
  datasources:
  - "file=./file.yaml"
  datasourceheaders: []:
test_val: 'abc'def'
```
