### ISSUE TITLE
Including multi-line files via gomplate breaks the config

### ISSUE THREAD

**Issue by simt2** [cisco-sso/mh#28]
I tried to include a multi-line file via gomplate like this: 
mh.yaml
```yaml
targetContext: minikube

gomplate:
  datasources:
  - "cassandra-grafana-dashboard=./cassandra-grafana-dashboard.json"
  datasourceheaders: []

rawCassandraGrafanaDashboard:
  resources:
  - apiVersion: v1
    metadata:
      name: cassandra-grafana-dashboard
    kind: ConfigMap
    spec:
      data:
        cassandra-dashboard.json: |-
[[ include "cassandra-grafana-dashboard" | indent 10 ]]
```

Running `mh simulate` fails with:
```
WARN[0000] Failed to load mh config. Please consider exporting environment variable: MH_CONFIG.  configFile=/Users/sitesar/src/go/src/github.com/cisco-sso/mh/main.yaml configFileEnv=/Users/sitesar/src/go/src/github.com/cisco-sso/mh/main.yaml configFileEnvPresent=true configFileFlag= configFileOrigin=env configFileUsed=/Users/sitesar/src/go/src/github.com/cisco-sso/mh/main.yaml err="While parsing config: yaml: line 18: could not find expected ':'"
FATA[0000] `kubectl config current-context` does not match configured targetContext  command=simulate currentContext=minikube targetContext=localhost
```

mh parses `MH_CONFIG` before it runs any command to sanity check the kubectl context, but with this kind of templating,  `MH_CONFIG` isn't valid YAML anymore.
