### ISSUE TITLE
[Feature] Allow splitting up of main.yaml into subfiles

### ISSUE THREAD

**Issue by rustycl0ck** [cisco-sso/mh#5]
As the number of apps grows, the `main.yaml` mh config file becomes very huge (~2000+ lines in some cases). Thus it would be convenient if the values for some apps can be provided from external files (preferably in the scope of mh config directories). A rough example would be as follows:

Current pattern:
```yaml
apps:
  - name: my-chart-0.1.0
    key: .myChart
    alias: my-chart

myChart:
  key1: value1
  key2: value2
   .. : ..
  key30: value30
```

Expected pattern:
```yaml
apps:
  - name: my-chart-0.1.0
    key: .myChart
    alias: my-chart

myChart:
  file: myChart-values.yaml
```

This would make it easier to manage the app values separately for each app and will also make the mh config file much cleaner if some app requires a lot of properties to be set.
